fossasia/open-event-android

app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java
app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java
app/src/main/java/org/fossasia/openevent/fragments/SponsorsFragment.java
app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java

In api/processor/*, for every success we are clearing the respective tables of database and adding new values.So, for every onRefresh(),its will clear the tables only when we have completed fetching that data else retain it.

 Fixed #117 #88

---

.travis.yml
app/build.gradle
app/src/main/java/org/fossasia/openevent/utils/StringUtils.java
codestyle.sh

Adds some much needed codestyle checks so we can move away from eye-balling the code for un-necessary things.

Codestyle relevant checks.

---

app/build.gradle

two reasons -
1. This will help test that the shipping branch works at it should
2. We need to get from v0.1 to something larger than 0.7 because tags
till 0.7 are already made
3. Semantic versioning !

bump version to 0.8.0

---

app/src/main/java/org/fossasia/openevent/utils/SpeakerIntent.java

Now, when the user clicks on speaker's linked in profile icon it opens directly in linkedin app, rather than in the browser.

LinkedIn app support added

---

app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java
app/src/main/java/org/fossasia/openevent/activities/SpeakersActivity.java
app/src/main/java/org/fossasia/openevent/dbutils/DatabaseOperations.java
app/src/main/java/org/fossasia/openevent/dbutils/DbSingleton.java
app/src/main/java/org/fossasia/openevent/fragments/BookmarksFragment.java

Fixed #319 : When any Session Details is opened either through Bookmarks,Speakers,Location Fragment, **track details was missing.**

Added Missing Track Details in Session details

---

app/src/main/java/org/fossasia/openevent/activities/MainActivity.java

@mananwason @championswimmer 
Automatically hide the keyboard if user touches outside it or opens the navigation drawer.
This fixes #222 and #198.
This is a better alternative to  #249 as there are fewer lines of code and it fixes both issues at once.
Cheers.

Auto Hide keyboard on clicking outside & on opening navigation drawer.

---

app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
app/src/main/java/org/fossasia/openevent/dbutils/DatabaseOperations.java
app/src/main/java/org/fossasia/openevent/dbutils/DbSingleton.java
app/src/main/java/org/fossasia/openevent/fragments/BookmarksFragment.java
app/src/main/res/layout/fragment_bookmarks.xml

Fixes #338.
Added a simple check once the user presses the Bookmarks option on NavDrawer. If no bookmarks exist, it shows up a prompt rather than lead him to an empty screen, thus saving time of the user. So the BookmarksFragment gets loaded only when some sessions are bookmarked.
Also, if we un-bookmark a session and the Bookmarks list becomes empty again, it shows up the dialog on pressing the back button on that Session Detail, and clicking on OK loads the TracksFragment back again.
This also happens to be one of the layout changes suggested in [my proposal](https://docs.google.com/document/d/1P1-UE0PFEE6KAnYhrdkRBmqzgYoUnN1ZFWQeC_p_mh4/edit), to reduce the blankiness in the application.
@championswimmer @mananwason @juslee

Fixed Redundant empty Bookmarks Page

---

apk-generator/scripts/buildApk.sh

@the-dagger @mariobehling This commit adds the functionality to send the signed and zip aligned apk to organiser, so now the organiser just has to upload this apk on the play store account.

added code to sign and send the signed release apk

---

.travis.yml

The Android Support Library and Google Play Services Library are deprecated and use of the repositories is recommended. This project has both so this will save some time. Fixes #642.

Speedup Travis CI build (Fixes #642)

---

android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java

pressing back when any other screen except "tracks" is selected reverts view to tracks but navigation view is not getting updated properly.
fixes #649.

fixes #649.

---

android/app/src/main/res/layout/nav_header.xml

fixes #880 : Added background color to navigation header and changed twitter logo to fossasia logo.           This was previous look:
This is new look:

fixed #880 : Added background color to navigation header and changed twitter logo to fossasia logo

---

android/app/src/fdroid/java/org/fossasia/openevent/fragments/OSMapFragment.java
android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java
android/app/src/main/java/org/fossasia/openevent/utils/ConstantStrings.java

Fixes issue #1054
Location of every event is accurately displayed on map, by passing session id through shared preferences.

Location of every event displayed accurately on map

---

android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java
android/app/src/main/res/layout/content_session_detail.xml
android/app/src/main/res/values/strings.xml

Fixes #1130 
- changed the content_session_detail (Added Grid layout).
- added trim() on date , endTime, startTime to remove trailing spaces. 

Session Layout Fixed  Fix issue#1130

---

android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java

**Fix: Navigation drawer abruptness while closing**
Whenever drawer closes or opens, the app should not perform heavy operations. Therefore a stutter or lag was observed. Now, the activity remains idle for that period of time when animation is being displayed and that eliminated the abruptness
Fixes #1173

Fix: navigation drawer lag #1173

---

android/app/src/main/java/org/fossasia/openevent/fragments/DayScheduleFragment.java
android/app/src/main/java/org/fossasia/openevent/fragments/SpeakersListFragment.java
android/app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java

Fixes #1218 
Changes: Now when refreshed, only those items which matches with search query are displayed.

Fix: Showing result based on query after refresh

---

android/app/src/fdroid/java/org/fossasia/openevent/fragments/OSMapFragment.java

Fixes #1219 
Changes: Corrected map location. Checked if microlocation is (0,0) i.e if latitude or longitude of microlocation is not given in api, then displayed event location.

Fix: Correcting map location

---

upload-apk.sh

Fixes #1094: Reduce Size of Repository by optimizing apk upload script.
Changes: The apk branch needs to maintain only the latest apk so maintaining all previous APKs doesn't make sense. After this, only latest APK will be maintained in APK branch. Same approach was used in Susi Android by me.

Fixes #1094: Reduces Size of Repository

---

android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java

#1185 
Changes: In SessionDetailActivity summary is not correctly parsed. Also the link is not clickable.
**## Before**
**# After** 
Please review this PR.

Correctly parse HTML in the Speaker Detail Activity #1185

---

android/app/src/main/res/values/strings.xml
apk-generator/v2/app/generator/generator.py
docs/android-app-setup.md
docs/installation/docker.md

patch contains some spelling fixes ( just in comments ) as found by a bot ( https://github.com/ka7/misspell_fixer ). Any upcoming License changes (e.g. GPL2 to GPL3+) are hereby granted.
one thing that makes me wonder:
( in open-event-android/apk-generator/v2/app/generator/generator.py )
-        elif 'Verification succesful' in output_line:
+        elif 'Verification successful' in output_line:
is this an local error (so this patch fixes it) or an upstream error ? if wrong, I can take it out...

spelling fixes

---

android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java

Fixes #1301 
Changes: 
Now when the user unbookmark all the bookmarked events and is taken to the tracks activity after that, the item selected in the navigation drawer would be of the "tracks" one.

fix: bug in item selection in navigation drawer resolved

---

android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java
android/app/src/main/java/org/fossasia/openevent/utils/NetworkUtils.java

Fixes #1277 
Changes: 
Added a network listener to listen for network change and consequently display speaker image when user changes the network settings.

fix: loading of SpeakerImage in SpeakerDetailsActivity resolved

---

android/app/src/main/java/org/fossasia/openevent/activities/TrackSessionsActivity.java

Fixes #1423 
Changes:  When user return from session detail activity, onResume method get call. I added code for checking search text in onResume method.

fix : search not working properly in track session activity

---

android/app/src/main/res/layout/fragment_schedule.xml

Fixes #1491
Changes: The tab layout was simply made of type "scrollable"

Scrollable tab in schedule fragment

---

android/app/src/main/res/layout/fragment_schedule.xml

DayScheduleFragment tabs not aligned properly.

---

android/app/src/main/java/org/fossasia/openevent/adapters/SpeakersListAdapter.java

Fixes #1646 
Changes:
Speaker image placeholder is displayed even if the internet is off and the user has opened the app for the first time.

fix: speaker image placeholder problem resolved

---

android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java

Fixes #1670 
Changes: The sponsors are sorted by ascending order of "level" in JSON, so that the sponsor with level:"1" comes at the top of the sponsors recycler view.

Updated sponsor's sort

---

android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java

Fixes #1651
Changes: 
When there aren't any sessions, only the map of the locations is displayed and not the "no sessions" text.
The back button directly leads to sessions list with the text "no session", as expected.

Fixed minor UI bugs in location activity
