fossasia/open-event-android

- LICENSE.md
- README.md
> add GPLv3 license

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/fossasia/openevent/OpenEventApp.java
- app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- app/src/main/java/org/fossasia/openevent/api/APIClient.java
- app/src/main/java/org/fossasia/openevent/api/Urls.java
- app/src/main/java/org/fossasia/openevent/api/network/OpenEventAPI.java
- app/src/main/java/org/fossasia/openevent/api/processor/EventListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/MicrolocationListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/SessionListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/SpeakerListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/SponsorListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/TrackListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/protocol/EventResponseList.java
- app/src/main/java/org/fossasia/openevent/data/Event.java
- app/src/main/java/org/fossasia/openevent/data/Microlocation.java
- app/src/main/java/org/fossasia/openevent/data/Session.java
- app/src/main/java/org/fossasia/openevent/data/Speaker.java
- app/src/main/java/org/fossasia/openevent/data/Sponsor.java
- app/src/main/java/org/fossasia/openevent/data/Track.java
- app/src/main/java/org/fossasia/openevent/dbutils/DataDownload.java
- app/src/main/java/org/fossasia/openevent/dbutils/DbContract.java
- app/src/main/java/org/fossasia/openevent/dbutils/DbHelper.java
- app/src/main/java/org/fossasia/openevent/dbutils/DbSingleton.java
- app/src/main/res/values/strings.xml
> insertion in database done

- app/src/main/java/org/fossasia/openevent/api/processor/EventListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/SessionListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/SpeakerListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/protocol/EventResponseList.java
- app/src/main/java/org/fossasia/openevent/data/Event.java
- app/src/main/java/org/fossasia/openevent/data/Session.java
- app/src/main/java/org/fossasia/openevent/data/SessionSpeakersMapping.java
- app/src/main/java/org/fossasia/openevent/data/Speaker.java
- app/src/main/java/org/fossasia/openevent/dbutils/DataDownload.java
- app/src/main/java/org/fossasia/openevent/dbutils/DbContract.java
- app/src/main/java/org/fossasia/openevent/dbutils/DbSingleton.java
> Fixes, SessionSpeaker relation added in db

- app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- app/src/main/java/org/fossasia/openevent/api/network/OpenEventAPI.java
- app/src/main/java/org/fossasia/openevent/api/processor/VersionApiProcessor.java
- app/src/main/java/org/fossasia/openevent/api/protocol/VersionResponseList.java
- app/src/main/java/org/fossasia/openevent/data/Version.java
- app/src/main/java/org/fossasia/openevent/dbutils/DataDownload.java
- app/src/main/java/org/fossasia/openevent/dbutils/DbContract.java
- app/src/main/java/org/fossasia/openevent/dbutils/DbHelper.java
- app/src/main/java/org/fossasia/openevent/dbutils/DbSingleton.java
@creativepsyco Please check and merge
> Database Versioning Completed

- app/src/androidTest/java/org/fossasia/openevent/DatabaseTest.java
- app/src/androidTest/java/org/fossasia/openevent/SpeakerInsertTest.java
- app/src/androidTest/java/org/fossasia/openevent/SponsorInsertTest.java
- app/src/androidTest/java/org/fossasia/openevent/TracksInsertTest.java
- app/src/fdroid/java/org/fossasia/openevent/fragments/OSMapFragment.java
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/fossasia/openevent/Adapters/TracksListAdapter.java
- app/src/main/java/org/fossasia/openevent/activities/TracksActivity.java
- app/src/main/java/org/fossasia/openevent/dbutils/DbSingleton.java
- app/src/main/java/org/fossasia/openevent/fragments/BookmarksFragment.java
- app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java
- app/src/main/java/org/fossasia/openevent/utils/RecyclerItemClickListener.java
- app/src/main/res/layout/activity_tracks.xml
> Database test

- app/build.gradle
- app/src/androidTest/java/org/fossasia/openevent/DatabaseTest.java
- app/src/androidTest/java/org/fossasia/openevent/SpeakerInsertTest.java
- app/src/androidTest/java/org/fossasia/openevent/SponsorInsertTest.java
- app/src/androidTest/java/org/fossasia/openevent/TracksInsertTest.java
- app/src/main/java/org/fossasia/openevent/Adapters/SpeakersListAdapter.java
- app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- app/src/main/java/org/fossasia/openevent/api/Urls.java
- app/src/main/java/org/fossasia/openevent/api/network/OpenEventAPI.java
- app/src/main/java/org/fossasia/openevent/data/Event.java
- app/src/main/java/org/fossasia/openevent/data/Microlocation.java
- app/src/main/java/org/fossasia/openevent/data/Session.java
- app/src/main/java/org/fossasia/openevent/data/Speaker.java
- app/src/main/java/org/fossasia/openevent/data/Sponsor.java
- app/src/main/java/org/fossasia/openevent/data/Track.java
- app/src/main/java/org/fossasia/openevent/dbutils/DbContract.java
- app/src/main/java/org/fossasia/openevent/dbutils/DbHelper.java
- app/src/main/java/org/fossasia/openevent/dbutils/DbSingleton.java
- app/src/main/java/org/fossasia/openevent/utils/CircleTransform.java
- app/src/main/java/org/fossasia/openevent/utils/SqlEscapeString.java
- app/src/main/java/org/fossasia/openevent/utils/randomStringGenerator.java
- app/src/main/res/layout-v21/speakers_item.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values/color.xml
- app/src/main/res/values/styles.xml
@creativepsyco Please review and merge. I  am not squashing these commits as they are different features.
> Speaker fragment, drawer ui improvements

- app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java
- app/src/main/java/org/fossasia/openevent/activities/SpeakersActivity.java
- app/src/main/java/org/fossasia/openevent/activities/TracksActivity.java
- app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java
- app/src/main/java/org/fossasia/openevent/adapters/SpeakersListAdapter.java
- app/src/main/java/org/fossasia/openevent/adapters/SponsorsListAdapter.java
- app/src/main/java/org/fossasia/openevent/adapters/TracksListAdapter.java
- app/src/main/java/org/fossasia/openevent/fragments/BookmarksFragment.java
- app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java
- app/src/main/java/org/fossasia/openevent/fragments/SponsorsFragment.java
- app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java
> refactor Adapters -> adapters

- app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- app/src/main/java/org/fossasia/openevent/activities/SpeakersActivity.java
- app/src/main/java/org/fossasia/openevent/api/Urls.java
- app/src/main/java/org/fossasia/openevent/api/processor/TrackListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/data/Event.java
- app/src/main/java/org/fossasia/openevent/data/Session.java
- app/src/main/java/org/fossasia/openevent/data/Speaker.java
- app/src/main/java/org/fossasia/openevent/data/Sponsor.java
- app/src/main/java/org/fossasia/openevent/data/Track.java
- app/src/main/java/org/fossasia/openevent/dbutils/DatabaseOperations.java
- app/src/main/java/org/fossasia/openevent/utils/SpeakerIntent.java
@creativepsyco Should we merge this right now?
> made app re:Data compatible

- app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- app/src/main/res/menu/drawer.xml
- app/src/main/res/values-pl/strings.xml
GCI task: https://codein.withgoogle.com/dashboard/task-instances/5039945412509696/
I've also replaced hardcoded strings in res/menu/drawer.xml to string resources to make the translations work.
> Add Polish translation

- app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
> Fix fragment management on orientation change

- README.md
Added Install/Config Instructions
> Added Install/Config Instructions

- app/src/main/res/layout/sessions_detail.xml
#110 Added Scroll View in SessionDetail Activity
> FIXED #110 Scrolling Effect Added in Session Detail Activity

- app/src/main/java/org/fossasia/openevent/dbutils/DatabaseOperations.java
On clicking on any member starting from member number 6 (i.e starting from guy named Tarek Ahmed) either app get crashed or lead us to the home screen. It is giving CursorIndexOutOfBoundsException.
I have resolved the issue and now it is working fine for all the rest members of the list as well.
> App crashing on clicking on any member  after 5th member on speaker's list #107 FIXED

- app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java
Clicking on time will now lead user to add the event to their calendar, with most of the options pre-filled. With reference to #118
> Add to calendar feature added

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/fossasia/openevent/OpenEventApp.java
- app/src/main/java/org/fossasia/openevent/Receivers/NetworkConnectivityChangeReceiver.java
- app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- app/src/main/java/org/fossasia/openevent/api/APIClient.java
- app/src/main/java/org/fossasia/openevent/api/Urls.java
- app/src/main/java/org/fossasia/openevent/api/processor/VersionApiProcessor.java
- app/src/main/java/org/fossasia/openevent/events/ConnectionCheckEvent.java
- app/src/main/java/org/fossasia/openevent/events/DataDownloadEvent.java
- app/src/main/java/org/fossasia/openevent/events/ShowNetworkDialogEvent.java
- app/src/main/res/values/strings.xml
I've come up with a system to handle errors as in Issue #127. It will show dialogs and give the respective error that has occurred.
For HTTP errors, it gives a dialog with the Error code too. For others, it gives a dialog with the type of error and the cause.
When network is unavailable, it gives a dialog to turn on network in Settings.
> Fixed Issue #127

- app/src/main/java/org/fossasia/openevent/api/processor/SpeakerListResponseProcessor.java
Fixed the typo in Issue #137. @mananwason
> Fixed typo in Issue #137

- app/src/main/res/layout/activity_speakers.xml
The required changes have been made with respect to #129 .
> Improved Scrolling for Speakers UI

- app/src/main/java/org/fossasia/openevent/utils/CircleTransform.java
@creativepsyco here is the new PR with updated code.Please review it. #121
> Application crashing on long scroll of speaker's list FIXED

- app/src/main/java/org/fossasia/openevent/Services/BookmarkAlarmService.java
- app/src/main/java/org/fossasia/openevent/dbutils/DbSingleton.java
> App Crashing on bookmarking any session #84 FIXED

- app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java
- app/src/main/java/org/fossasia/openevent/fragments/SponsorsFragment.java
Options menu is not needed in Sponsors fragment but yet it was visible. Removed the menu from Sponsors fragment.
> Remove options menu from Sponsors fragment

- app/src/main/java/org/fossasia/openevent/activities/LocationActivtiy.java
- app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- app/src/main/java/org/fossasia/openevent/activities/SpeakersActivity.java
- app/src/main/java/org/fossasia/openevent/activities/TracksActivity.java
- app/src/main/java/org/fossasia/openevent/api/Urls.java
- app/src/main/java/org/fossasia/openevent/fragments/BookmarksFragment.java
- app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java
- app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java
- app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java
- app/src/main/res/menu/menu_bookmarks.xml
App On Orientation Change,Search View and Search Text not Retained #122 ,FIXED
> FIXED: Search View on Orientation Change #122

- README.md
> add todofy badge - shows remaining todos

- app/src/main/java/org/fossasia/openevent/fragments/BookmarksFragment.java
- app/src/main/res/values/strings.xml
> FIXED #174

- app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- app/src/main/res/menu/drawer.xml
- app/src/main/res/values/strings.xml
Fixed up about section for pull request #179
> Vjs3 local

- app/src/main/java/org/fossasia/openevent/activities/SpeakersActivity.java
- app/src/main/java/org/fossasia/openevent/utils/SpeakerIntent.java
Also, showing a Toast instead of hiding the ImageView, which I think provides better UI experience.
Signed-off-by: Suhaib Khan <suheb.work@gmail.com>
> Fixes: Clicking on speaker social profile with no link results in app crash #182

- app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
> #188 UI BUG Fixed

- app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
Also, removed extra blank lines and redundant comments. @creativepsyco
> Fixed #191

- app/src/main/res/layout/activity_speakers.xml
- app/src/main/res/layout/activity_splash.xml
- app/src/main/res/values/dimens.xml
Also updating splash screen image.
Screenshots:
Before:
After:
Before:
After:
Signed-off-by: Suhaib Khan <suheb.work@gmail.com>
> Small UI improvements in speaker and sponsor sections.

- app/src/main/java/org/fossasia/openevent/activities/TracksActivity.java
- app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java
- app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java
The search results was not refreshing on clearing all the texts. Fixed
> Added Some Missing Refresh Options

- app/src/main/res/layout/activity_locations.xml
- app/src/main/res/layout/activity_speakers.xml
- app/src/main/res/values-v21/styles.xml
Fixed incorrect Statusbar color and Toolbar icon colors.
> Fixed issues #231,#217 and #227

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java
- app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java
I thought this should be a part of a separate commit, so sent a PR for this separately. It's a typo but still.
> LocationActivity name is wrong

- app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java
Fix for #215. @mananwason @creativepsyco
> Fixed Bookmark Notifications

- app/src/main/AndroidManifest.xml
Fixed the issue where the app would restart instead on closing when back button was pressed.
Fix is for issue #228 
@championswimmer @mananwason
> Fixed restart on pressing the back button

- app/src/main/java/org/fossasia/openevent/Services/BookmarkAlarmService.java
Fixes: #244 
Signed-off-by: Suhaib Khan <suheb.work@gmail.com>
> Fixing bookmark notification icon for android 5.0

- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh/strings.xml
> remove untranslatable strings from language variants

- README.md
- codestyle.sh
> fix typos in codestyle.sh and README.md

- app/src/main/res/layout/activity_settings.xml
- app/src/main/res/values-v21/styles.xml
@championswimmer fixed issue https://github.com/fossasia/open-event-android/issues/217
> Fix wrong statusbar color in Settings Activity

- README.md
LeakCanary and Picasso are also used in the app.
> Updating list of Libraries

- app/src/fdroid/java/org/fossasia/openevent/fragments/OSMapFragment.java
#242 Permissions Added , and view gets populated after giving permissions
> Added missing Runtime Permission for  API >=23

- app/src/androidTest/java/org/fossasia/openevent/DatabaseTest.java
- app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java
- app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java
- app/src/main/java/org/fossasia/openevent/api/processor/EventListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/MicrolocationListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/SessionListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/SpeakerListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/SponsorListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/TrackListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/VersionApiProcessor.java
- app/src/main/java/org/fossasia/openevent/data/Session.java
- app/src/main/java/org/fossasia/openevent/dbutils/DbHelper.java
- app/src/main/java/org/fossasia/openevent/fragments/SponsorsFragment.java
- app/src/main/java/org/fossasia/openevent/utils/DownloadCounter.java
- app/src/main/java/org/fossasia/openevent/utils/ISO8601Date.java
Fixes #269.
I've added Timber.tag for those which have tags explicitly mentioned. And I removed the tags for some features which didn't need tags and could have tag as Activity name.
@championswimmer Please tell me if there are issues in this. I'll resolve them and squash commits.
> Converted to Timber

- build.gradle
> update android gradle plugin version to fix builds on travis

- app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
There's no need of adding any lines, removed a redundant line which solves this. Works fine. @championswimmer @mananwason
> Fixed multiple selection in NavDrawer

- app/src/main/res/menu/drawer.xml
@championswimmer 
Before
After
> Removed the empty space in navigation drawer

- app/build.gradle
- app/src/androidTest/java/org/fossasia/openevent/APITest.java
- app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- app/src/main/java/org/fossasia/openevent/api/APIClient.java
- app/src/main/java/org/fossasia/openevent/api/Urls.java
- app/src/main/java/org/fossasia/openevent/api/network/OpenEventAPI.java
- app/src/main/java/org/fossasia/openevent/api/processor/EventListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/MicrolocationListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/SessionListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/SpeakerListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/SponsorListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/TrackListResponseProcessor.java
- app/src/main/java/org/fossasia/openevent/api/processor/VersionApiProcessor.java
- app/src/main/java/org/fossasia/openevent/dbutils/DataDownloadManager.java
- build.gradle
update project to use Retrofit2.
-update test classes as well.
-added all required libraries.
**there is some minor changes left in error handling will be finished soon but there is no bugs introduced or behaviour changes.
> update project to use retrofit:2.0.0 from beta4 and fix all errors occurred as a result of this.

- app/src/main/res/layout/item_location.xml
- app/src/main/res/layout/item_speaker.xml
- app/src/main/res/layout/item_sponsor.xml
- app/src/main/res/layout/item_track.xml
@mananwason This is what @ahmed-fathy-aly was trying to do in #290 .
IMO, looks good, gives a material feeling to the app.
> Add Ripple Effect on clicking track, location, sponsor and speaker item.

- app/src/main/AndroidManifest.xml
> Adding Intent of App Notification Settings

- README.md
@mananwason @championswimmer Embed YouTube Video link for the app's walk-through,
> Embed YouTube Video link for the app

- app/src/main/java/org/fossasia/openevent/Services/BookmarkAlarmService.java
- app/src/main/res/layout/activity_locations.xml
list fatal errors are down to 0 now
> fix some lint errors

- app/src/main/java/org/fossasia/openevent/activities/TracksActivity.java
- app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java
- app/src/main/java/org/fossasia/openevent/dbutils/DatabaseOperations.java
Fixed #195 Search + Fixed #320 Session List within Tracks
> Fixed #195 Search + Fixed #320 Session List within Tracks

- README.md
@championswimmer @mananwason This one looks better, also I have added the Google Play store badge too.
> Add appetize.io and GPlay badge to Readme

- app/src/main/java/org/fossasia/openevent/api/processor/SpeakerListResponseProcessor.java
Fixed #348 Sessions in SpeakerDetails Activity
> Fixed #348 Sessions in SpeakerDetails Activity

- android/app/src/main/assets/config.json
- android/app/src/main/java/org/fossasia/openevent/OpenEventApp.java
- android/app/src/main/java/org/fossasia/openevent/Receivers/NotificationAlarmReceiver.java
- android/app/src/main/java/org/fossasia/openevent/Services/BookmarkAlarmService.java
- android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/SpeakersActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/TracksActivity.java
- android/app/src/main/java/org/fossasia/openevent/api/APIClient.java
- android/app/src/main/java/org/fossasia/openevent/api/Urls.java
- android/app/src/main/java/org/fossasia/openevent/fragments/BookmarksFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java
- android/app/src/main/java/org/fossasia/openevent/utils/ConstantStrings.java
This Pull request adds the functionality to the app to read a config file and extracts the name, api url from there. @mariobehling @the-dagger Please review.
> Added json config file parsing

- apk-generator/index.html
This will return a json object containing data entered by the user when he/she clicks the "Submit" button.
> Convert the input text in the form to json object

- apk-generator/index.html
Using firebase for now @mananwason and we'll later switch to our server.
#382
> Add updated website hosted on firebase to store entered data

- apk-generator/scripts/send_email.sh
As discussed in #389 
@mananwason @mariobehling
> Add apk folder as a argument for the script

- apk-generator/scripts/setPerm.sh
Fixes #409 
@mananwason @mariobehling Please review
> Add script to set permissions for folders in the server

- docs/ApkGenerator.md
Fixes #405 
@mananwason Please Review
> Add documentation for setting up the server

- apk-generator/scripts/appgenserver.py
@the-dagger This fixes #408. Please review and merge
> fixes #408

- apk-generator/index.html
- apk-generator/scripts/copyApk.sh
- apk-generator/scripts/runPy.php
Fixes #390 
@mananwason @mariobehling Please review.
> Add script to initiate download once apk has been compiled

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/fossasia/openevent/utils/NetworkUtils.java
@the-dagger Please review and merge
> fixes #310

- apk-generator/scripts/runPy.php
Fixes #425 
@mananwason Please review.
> Fix app not getting downloaded on firefox

- README.md
@mananwason please check and merge.
> Update Readme to reference to updated docs

- android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- android/app/src/main/java/org/fossasia/openevent/api/APIClient.java
- android/app/src/main/java/org/fossasia/openevent/api/processor/VersionApiProcessor.java
- android/app/src/main/java/org/fossasia/openevent/events/CounterEvent.java
- android/app/src/main/java/org/fossasia/openevent/events/EventDownloadEvent.java
- android/app/src/main/java/org/fossasia/openevent/events/MicrolocationDownloadEvent.java
- android/app/src/main/java/org/fossasia/openevent/events/RetrofitError.java
- android/app/src/main/java/org/fossasia/openevent/events/RetrofitResponseEvent.java
- android/app/src/main/java/org/fossasia/openevent/events/SessionDownloadEvent.java
- android/app/src/main/java/org/fossasia/openevent/events/SpeakerDownloadEvent.java
- android/app/src/main/java/org/fossasia/openevent/events/SponsorDownloadEvent.java
- android/app/src/main/java/org/fossasia/openevent/events/TracksDownloadEvent.java
- android/app/src/main/java/org/fossasia/openevent/events/VersionDownloadEvent.java
@the-dagger Please review and merge
> added error handling in retrofit 2

- apk-generator/index.html
- apk-generator/scripts/upload.php
- apk-generator/scripts/uploadHelper.php
@mananwason please review and merge.
Fixes #434
> Add script for uploading files

- android/app/src/main/java/org/fossasia/openevent/Services/BookmarkAlarmService.java
Fixes #428 
@mananwason Please review.
> Fixed crash on bookmark section

- android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- android/app/src/main/java/org/fossasia/openevent/api/APIClient.java
- android/app/src/main/java/org/fossasia/openevent/api/Urls.java
@the-dagger Please review and merge
> fixes #439

- README.md
- docs/AndroidApp.md
@the-dagger Please review and merge.
> Added android app docs

- android/app/build.gradle
- android/app/src/main/assets/speakers.json
- android/app/src/main/res/layout/activity_speakers.xml
- android/app/src/main/res/layout/bookmark_widget.xml
- android/app/src/main/res/layout/item_schedule.xml
- android/app/src/main/res/layout/item_speaker.xml
- android/app/src/main/res/layout/list_schedule.xml
- android/app/src/main/res/menu/drawer.xml
- android/app/src/main/res/menu/menu_schedule.xml
- android/app/src/main/res/values/styles.xml
Code cleanup and added json for #442
> refactor and code cleanup, added json for #442

- android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- android/app/src/main/res/layout/activity_main.xml
@mananwason @the-dagger Please review and merge.
> fixed issue #456

- android/app/src/main/java/org/fossasia/openevent/activities/SpeakersActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/TracksActivity.java
- android/app/src/main/res/layout/activity_speakers.xml
- android/app/src/main/res/layout/activity_tracks.xml
Fixed the CollapsibleToolbarLayout in TracksActivity.
> Fixed CollapsibleToolbarLayout - issue#465

- android/app/src/main/res/layout/tracksactvity_item.xml
> Fixed issue #471

- apk-generator/index.html
> Add upload functionality to firebase

- android/app/src/main/res/layout/item_track.xml
FIxes #454 .
@mananwason Please review and merge.
> Fix tracksActivity

- apk-generator/scripts/appgenserver.py
@the-dagger Please review and merge. Fixes #434 #436.
> added packaging of icon and json assets

- android/app/src/main/res/layout/item_sponsor.xml
> Fix sponsors logo taking up the whole space

- README.md
- docs/AndroidApp.md
Corrected the links in README.md.
In development setup, mentioned explicitly to move to android folder inside root directory to compile and run the app
> updated README.md and AndroidApp.md

- android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/SpeakersActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/TracksActivity.java
- android/app/src/main/java/org/fossasia/openevent/fragments/DayScheduleFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/ScheduleFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/SpeakerFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/SponsorsFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java
- android/app/src/main/res/layout/activity_locations.xml
- android/app/src/main/res/layout/activity_speakers.xml
- android/app/src/main/res/layout/activity_tracks.xml
- android/app/src/main/res/layout/list_locations.xml
- android/app/src/main/res/layout/list_schedule.xml
- android/app/src/main/res/layout/list_speakers.xml
- android/app/src/main/res/layout/list_sponsors.xml
- android/app/src/main/res/layout/list_tracks.xml
- android/app/src/main/res/values/strings.xml
> Fix empty spaces and codacy issues

- android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- android/app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java
- android/app/src/main/res/layout/list_locations.xml
- android/app/src/main/res/layout/list_sponsors.xml
@mananwason @mariobehling Fixes #513 
Please have a look and merge if it looks good.
> Fix tracks not getting updated after download

- apk-generator/api/api.php
- apk-generator/api/appgenserver.py
- apk-generator/api/composer.json
- apk-generator/api/email.php
- apk-generator/scripts/appgenserver.py
- apk-generator/scripts/config.json
- apk-generator/scripts/email.sh
- apk-generator/scripts/passapi.sh
Fixes #541 #545 #542 
@mariobehling @mananwason Please check
> Add files for SendGrid and fix other issues

- android/app/src/main/java/org/fossasia/openevent/adapters/SpeakersListAdapter.java
- android/app/src/main/res/layout/item_speaker.xml
@mariobehling @the-dagger Please review and merge.
> Fixes #565

- android/app/src/fdroid/java/org/fossasia/openevent/fragments/OSMapFragment.java
- android/app/src/googleplay/java/org/fossasia/openevent/fragments/MapsFragment.java
- android/app/src/main/java/org/fossasia/openevent/api/processor/EventListResponseProcessor.java
@the-dagger @mariobehling Please review and merge. This PR adds location markers to maps and fixes other implementation issues with maps.
> Fixes #564

- android/app/src/main/java/org/fossasia/openevent/activities/SpeakersActivity.java
- android/app/src/main/java/org/fossasia/openevent/data/Speaker.java
- android/app/src/main/res/layout/activity_speakers.xml
> Fix speakerDetail page

- apk-generator/api/appgenserver.py
- apk-generator/index.html
- apk-generator/scripts/appgenserver.py
- apk-generator/scripts/runPy.php
Fixes #595 
@mariobehling @mananwason Please merge
[skip ci]
> Script update [skip ci]

- README.md
- docs/AndroidApp.md
- docs/ServerSetup.md
@mananwason @mariobehling This fixes #546 
Please review and merge
> Update Documentation and add missing points to readme

- apk-generator/index.html
Fixes #543 
@mariobehling @mananwason Please review and merge.
> Add progressbar on the app generator

- apk-generator/index.html
Reverts fossasia/open-event-android#602
Implementation buggy.
> Revert "Add progressbar on the app generator"

- apk-generator/index.html
@mariobehling @mananwason This fixes #614 
The live site is here [http://45.55.58.149/](http://45.55.58.149/) 
Try uploading a file which is not zip and you will see the changes.
Please test and merge.
> Allow the user to upload only zip files

- apk-generator/index.html
- apk-generator/scripts/upload.php
Fixes #610 , for some reason the fix wasn't yet reflected in the source code.
> Fix multiple uploads

- android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
> Fixes issue #636

- .travis.yml
Reverts fossasia/open-event-android#641
> Revert "Speedup Travis CI build (Fixes #642)"

- .travis.yml
Proof that components are not required: 
Proof that MaxPermSize is not required:
@mananwason
> Remove unnecessary parameters and components

- apk-generator/index.html
Fixes #661 and #660 
@mananwason @mariobehling Please review and merge
> Cancel current file upload and fix label

- android/app/src/main/res/layout/nav_header.xml
- apk-generator/scripts/appgenserver.py
@mariobehling fixes #683 #668 
Please test it on the live site : [http://45.55.58.149/](http://45.55.58.149/)
> Resize image and exception handling for app's name

- android/app/src/main/java/org/fossasia/openevent/activities/BaseActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/TracksActivity.java
- android/app/src/main/java/org/fossasia/openevent/fragments/BaseFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/BookmarksFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/DayScheduleFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/ScheduleFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/SpeakersListFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/SponsorsFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java
Solution for #724 . As it was reverted back, sending a separate commit again.
> re-factor: setContentView and butterknife binding should be done in base activity and base fragment

- android/app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java
Fix: Refresh flow bug in Track Fragment
Resolves: #756
> Fix: Refresh flow bug in Track Fragment

- android/app/src/main/java/org/fossasia/openevent/activities/SettingsActivity.java
Fixes issue #759 back arrow button is not working in setting activity
> Fixes issue #759 back arrow button is not working in setting activity

- android/app/src/main/res/layout/activity_tracks.xml
Solving issue #777 . Toolbar of sessions activity scrolls smoothly.
> Making toolbar of sessions activity scrollable

- android/app/src/main/res/values-ja/arrays.xml
- android/app/src/main/res/values-ja/strings.xml
> Added Japanese translation

- android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/TracksActivity.java
- android/app/src/main/java/org/fossasia/openevent/fragments/BookmarksFragment.java
- android/app/src/main/res/layout/tracksactvity_item.xml
> solved #897

- android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java
- android/app/src/main/res/values/strings.xml
> Fixes #932

- README.md
- docs/INSTALLATION.md
- docs/INSTALLATION_AWS.md
- docs/INSTALLATION_DIGITALOCEAN.md
- docs/INSTALLATION_DOCKER.md
- docs/INSTALLATION_GOOGLE.md
- docs/INSTALLATION_HEROKU.md
- docs/INSTALLATION_LOCAL.md
- Fixed typos (navigae to navigate , mdify to modify, etc.)
- Fixed broken link to heroku documentation
- Added a more clear instruction (step no. 8) in all installation instruction files
- Added a new device in tested devices list
> - Fixed Typos , Broken link to heroku documentation , added a more clear instruction

- android/app/src/main/res/values-hi/strings.xml
- android/app/src/main/res/values-ta/strings.xml
- android/app/src/main/res/values/strings.xml
- Added Tamil localization support
- Improved hindi localization support
- Issue: https://github.com/fossasia/open-event-android/issues/947
- Task: https://codein.withgoogle.com/dashboard/task-instances/5086487165009920/
> Added Tamil localization support and improved hindi localization support

- android/app/src/main/res/values-id/arrays.xml
- android/app/src/main/res/values-id/strings.xml
This Pull request adds Indonesian translations to the strings and arrays.
Closes https://github.com/fossasia/open-event-android/issues/949
> Add Indonesian Translation

- android/app/src/main/res/values-ml/strings.xml
Added Malayalam localization support for the app
Closes issue #929 
Done as part of Google code-in task: https://codein.withgoogle.com/dashboard/task-instances/5307164463726592/
@the-dagger please review and merge
> Added Malayalam localization support

- android/app/src/main/res/values-ro/strings.xml
Improved the existing strings and added the missing ones, making the Romanian translation a complete one. @mananwason @the-dagger
> Improved Romanian support and added new strings

- android/app/src/main/res/values-es/strings.xml
With this PR, I improved the spanish support. If you have a doubt about the translations, my mother tongue is Spanish 😝  🇨🇴
> Improving the spanish support

- README.md
hello i found a grammatical issue on "upload.php A PHP script that will upload the json zip that is chosed by the user." 
Change word "chosed" to "chosen"
> Change word "chosed" to "chosen"

- android/app/build.gradle
- android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java
- android/app/src/main/java/org/fossasia/openevent/adapters/SponsorsListAdapter.java
- android/app/src/main/java/org/fossasia/openevent/fragments/SponsorsFragment.java
- android/app/src/main/java/org/fossasia/openevent/utils/SpeakerIntent.java
- android/app/src/main/java/org/fossasia/openevent/views/CustomTabsSpan.java
- android/app/src/main/res/anim/slide_in_right.xml
- android/app/src/main/res/anim/slide_out_right.xml
@mananwason @the-dagger Review and let me if any changes required. :)
> Fixes: #922 URL opens up in chrome custom tabs

- android/app/src/main/res/layout/activity_sessions_detail.xml
Fixes #1128 
- changed fab layout in activity_sessions_detail
> Fixes Issue #1128

- android/app/src/main/java/org/fossasia/openevent/views/MarginDecoration.java
- android/app/src/main/res/layout/activity_locations.xml
- android/app/src/main/res/layout/activity_sessions_detail.xml
- android/app/src/main/res/layout/activity_speakers.xml
- android/app/src/main/res/layout/bookmark_widget.xml
- android/app/src/main/res/layout/content_session_detail.xml
- android/app/src/main/res/layout/fragment_bookmarks.xml
- android/app/src/main/res/layout/item_location.xml
- android/app/src/main/res/layout/item_schedule.xml
- android/app/src/main/res/layout/item_speaker.xml
- android/app/src/main/res/layout/item_sponsor.xml
- android/app/src/main/res/layout/item_sponsor_type.xml
- android/app/src/main/res/layout/item_track.xml
- android/app/src/main/res/layout/list_speakers.xml
- android/app/src/main/res/layout/nav_header.xml
- android/app/src/main/res/layout/tracksactvity_item.xml
- android/app/src/main/res/layout/widget_list_item.xml
- android/app/src/main/res/values/dimens.xml
made changes to the dimens.xml.
> fixes #1095: changed dimens.xml and the consequent layout files

- android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- android/app/src/main/java/org/fossasia/openevent/fragments/BookmarksFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/DayScheduleFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/SpeakersListFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/SponsorsFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java
Fixes #1123 
Changes: 
1. The app bar expands when we scroll down.
2. While going from one fragment to another the app bar expands.
> Fixed collapsed appbar.

- android/app/src/main/java/org/fossasia/openevent/fragments/BookmarksFragment.java
Fixes #1202 
Changes: App not crashing now.
> Fix: App crashing in bookmarks fragment.

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/fossasia/openevent/OpenEventApp.java
- android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- android/app/src/main/java/org/fossasia/openevent/api/Urls.java
- android/app/src/main/java/org/fossasia/openevent/api/processor/EventListResponseProcessor.java
- android/app/src/main/java/org/fossasia/openevent/data/Version.java
Changes to make app working with FOSSASIA 2017
Fixes #1149 
Changes: [Add here what changes were made in this issue and if possible provide links.]
> App tested with FOSSASIA 2017 api

- android/app/src/main/java/org/fossasia/openevent/adapters/DayScheduleAdapter.java
Fixes #1231 
Changes: 
Removal of html tags.
> fix: removing html tags from scheduleFragment

- android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/TrackSessionsActivity.java
- android/app/src/main/java/org/fossasia/openevent/fragments/BookmarksFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/SpeakersListFragment.java
Fixes #1206 
Changes: Now when rotated, the layout comes back to its normal form.
> Fix: Corrected the grid layout when screen is rotated.

- docs/installation/kubernetes.md
Fixes #1210 
Changes: 
updated kubernetes.md with an installation guide.
-
> fix: updated kubernetes.md

- android/app/src/androidTest/java/org/fossasia/openevent/DatabaseTest.java
- android/app/src/main/java/org/fossasia/openevent/dbutils/DatabaseOperations.java
> fix: Access to package method in DatabaseTest

- android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java
Fixes #1238 
Changes: 
Resolved bookmark status issue in SpeakerDetailActivity
> fix: issue bookmark status in SpeakerDetailsActivity resolved

- android/app/src/main/java/org/fossasia/openevent/dbutils/DatabaseOperations.java
Fixes #1280 
Changes: Changed the sort order to descending
> fix: issue Sort Sponsors according to sponsorship level

- android/app/src/main/java/org/fossasia/openevent/adapters/DayScheduleAdapter.java
- android/app/src/main/java/org/fossasia/openevent/adapters/LocationsListAdapter.java
- android/app/src/main/java/org/fossasia/openevent/adapters/TracksListAdapter.java
- android/app/src/main/java/org/fossasia/openevent/fragments/DayScheduleFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java
- android/app/src/main/java/org/fossasia/openevent/views/stickyheadersrecyclerview/HeaderPositionCalculator.java
- android/app/src/main/java/org/fossasia/openevent/views/stickyheadersrecyclerview/ItemVisibilityAdapter.java
- android/app/src/main/java/org/fossasia/openevent/views/stickyheadersrecyclerview/StickyRecyclerHeadersAdapter.java
- android/app/src/main/java/org/fossasia/openevent/views/stickyheadersrecyclerview/StickyRecyclerHeadersDecoration.java
- android/app/src/main/java/org/fossasia/openevent/views/stickyheadersrecyclerview/StickyRecyclerHeadersTouchListener.java
- android/app/src/main/java/org/fossasia/openevent/views/stickyheadersrecyclerview/caching/HeaderProvider.java
- android/app/src/main/java/org/fossasia/openevent/views/stickyheadersrecyclerview/caching/HeaderViewCache.java
- android/app/src/main/java/org/fossasia/openevent/views/stickyheadersrecyclerview/calculation/DimensionCalculator.java
- android/app/src/main/java/org/fossasia/openevent/views/stickyheadersrecyclerview/rendering/HeaderRenderer.java
- android/app/src/main/java/org/fossasia/openevent/views/stickyheadersrecyclerview/util/LinearLayoutOrientationProvider.java
- android/app/src/main/java/org/fossasia/openevent/views/stickyheadersrecyclerview/util/OrientationProvider.java
- android/app/src/main/res/layout/item_schedule.xml
- android/app/src/main/res/layout/recycler_view_header.xml
Fixes #1291 
Changes: 
-Added StickyHeaderRecyclerView in java/org/fossasia/openevent/views
-Implemented StickyRecyclerHeadersAdapter in TracksListAdapter, DayScheduleAdapter, LocationsListAdapter
-Added StickyRecyclerHeadersDecoration in TracksFragment, ScheduleFragment, LocationsFragment
-Changed layout of schdule item
-Improve UI and UX.
-Update to Sticky Header Recycler view for grouping of Recyclerview items which starts with same Alphabet or time which will improve UI and UX.
> Ui improvement : Update RecyclerView to StickyHeadersRecyclerView

- android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java
Fixes #1312 
Changes:
Resolved crashing and now the app is working fine.
> fix: resolved crashing in SpeakerDetailsActivity

- android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/TrackSessionsActivity.java
Fixes #1306
Changes: mSessions list cleared before adding new items.
> Fix: Arraylist not cleared before adding items

- android/app/src/main/res/layout/bookmark_widget.xml
> fix:Missing Logo in Bookmark Widget added(#1300)

- android/app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java
Fixes #1357 
**Earlier**
**Now**
> improved location fragment ui

- android/app/src/fdroid/java/org/fossasia/openevent/fragments/OSMapFragment.java
Fixes #1389 
Changes: [Add here what changes were made in this issue and if possible provide links.]
> fix: Fix crashing OSMapFragment (#1389)

- android/app/src/main/java/org/fossasia/openevent/adapters/DayScheduleAdapter.java
- android/app/src/main/java/org/fossasia/openevent/fragments/DayScheduleFragment.java
- android/app/src/main/java/org/fossasia/openevent/fragments/ScheduleFragment.java
- android/app/src/main/res/drawable/ic_close_24dp.xml
- android/app/src/main/res/drawable/ic_filter_24dp.xml
- android/app/src/main/res/drawable/ic_plus_24dp.xml
- android/app/src/main/res/layout/fragment_schedule.xml
- android/app/src/main/res/menu/menu_schedule.xml
- android/app/src/main/res/values/strings.xml
Fixes #1412 
Changes: Now user can filter the schedule based on tracks. Also, shifted sort from actionbar to fab.
> feat: Adding feature to filter schedule

- android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
Fixes #1447 
Changes: 
Reference correct image header in Navigation View and load event icon
> fix: Show correct event logo in Navigation View

- docs/apk-generator.md
Fixes #1436
Add details about the app generation process in web app
> docs: Add app build details in apk-generator.md

- android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java
Fixes #1407
Changes:
- SessionDetailActivity.java
> Fixed SessionDetailActivity AppBarLayout not collapsing appropriately

- android/app/src/main/res/layout/fragment_bookmarks.xml
> removed padding from fragment_bookmarks.xml

- android/app/build.gradle
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
Update the support lib version and gradle plugin for the repo.
> update support lib and gradle plugin

- android/app/src/main/java/org/fossasia/openevent/fragments/DayScheduleFragment.java
Fixes #1489 
Changes: 
Actually the hashmap is causing the memory leak problem. Resolved it.
-
> fix: resolved the memory leak in DayScheduleFragment

- android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/SettingsActivity.java
- android/app/src/main/res/anim/slide_in_left.xml
- android/app/src/main/res/anim/slide_in_right.xml
- android/app/src/main/res/anim/slide_out_left.xml
- android/app/src/main/res/anim/stay_in_place.xml
- android/app/src/main/res/values/strings.xml
- android/app/src/main/res/xml/settings.xml
Fixes #1444 
Changes: default anim files were changed to give a shortConfigTIme and the Handler for the intent was removed.
Already in Issue
> fix:Settings Page Animation fixed and Settings Descriptions Added(#1444)

- android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java
- android/app/src/main/java/org/fossasia/openevent/data/Speaker.java
> Fixes message sharing issue

- android/app/build.gradle
- android/app/src/main/java/org/fossasia/openevent/OpenEventApp.java
- android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- android/app/src/main/res/layout/dialog_share.xml
Fixes #1493
Removed "sharing with Facebook" button and restructured "sharing with app".
> share button updated

- android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java
Fixes #1531 
Changes: 
Toolbar displayed on map icon click in SessionDetailActivity.
> fix: displayed toolbar for map icon click

- android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java
- android/app/src/main/res/layout/activity_locations.xml
- android/app/src/main/res/menu/menu_location_activity.xml
Fixes #1475 
Changes: 
Added maps icon to location acitvity so that user can directly view the location on the maps.
> feat: added map icon in location activity

- docs/installation/generic.md
Added OSX documentation for app generator generic installation
Fixes #1574
> OSX docs for generic installation of app generator

- android/app/src/main/java/org/fossasia/openevent/OpenEventApp.java
- android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- android/app/src/main/java/org/fossasia/openevent/utils/ConstantStrings.java
- android/app/src/main/res/values/strings.xml
Fixes #1560 
Changes:
Now event specific info like its description, name etc. are taken from json files instead of hard coding it in the strings.xml file.
-
> fix: taking event specific info from assets folder

- android/app/src/main/java/org/fossasia/openevent/api/processor/SpeakerListResponseProcessor.java
Fixes #1620 
Changes: Handles the exception by using an` if` statement to execute the speaker's session `for` loop only when the session's array list is not empty.
> fixes nullpointer exception in SpeakerListResponseProcessor.java

- android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java
Fixes #1622 About action bar back button in location activity not responsive.
Changes: Created a case in `onOptionsItemSelected() `to handle the event of clicking the home button.
> back button in location activity made working

- android/app/src/androidTest/java/org/fossasia/openevent/DateTest.java
Fixes #1549 
Changes:
Added tests for date testing.
-
> test: date tests added

- android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java
Fixes  #1636 and #1551 
Changes:
> Update location activity map activity

- android/app/src/main/java/org/fossasia/openevent/adapters/TracksListAdapter.java
- android/app/src/main/java/org/fossasia/openevent/data/Track.java
- android/app/src/main/res/layout/item_track.xml
Fixes #1673
Changes: 
Removed the description and location tag from realm for tracks.
-
> fix: removed certain attributes from tracks

- android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java
- android/app/src/main/java/org/fossasia/openevent/utils/ConstantStrings.java
- android/app/src/main/res/drawable-v21/ic_play.xml
- android/app/src/main/res/layout/content_session_detail.xml
Fixes #1609 
Changes: 
Added a video button in the SessionDetailActivity.java.
<details>
<summary>Click to view image</summary>
</details>
> feat: added video button

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java
- android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java
- android/app/src/main/java/org/fossasia/openevent/adapters/GlobalSearchAdapter.java
- android/app/src/main/java/org/fossasia/openevent/adapters/LocationsListAdapter.java
- android/app/src/main/java/org/fossasia/openevent/adapters/SessionSpeakerListAdapter.java
- android/app/src/main/java/org/fossasia/openevent/adapters/SpeakersListAdapter.java
- android/app/src/main/java/org/fossasia/openevent/adapters/TracksListAdapter.java
- android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/LocationViewHolder.java
- android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/SpeakerViewHolder.java
- android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/TrackViewHolder.java
- android/app/src/main/java/org/fossasia/openevent/events/EventLoadedEvent.java
- android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java
- android/app/src/main/res/layout/activity_search.xml
- android/app/src/main/res/layout/fragment_about.xml
- android/app/src/main/res/layout/fragment_bookmarks.xml
- android/app/src/main/res/layout/item_session_speaker.xml
- android/app/src/main/res/layout/search_item_speaker.xml
- android/app/src/main/res/layout/search_result_type_header_format.xml
- android/app/src/main/res/menu/drawer.xml
- android/app/src/main/res/menu/menu_home.xml
- android/app/src/main/res/values-w820dp/dimens.xml
- android/app/src/main/res/values/color.xml
- android/app/src/main/res/values/dimens.xml
- android/app/src/main/res/values/strings.xml
- android/app/src/main/res/xml/searchable.xml
feat:Global Search Added along with Bookmarks added to Home Page(#1499)
First steps for issues #1499 
Screenshots have been posted in the Issue itself
> feat:New Home+Bookmarks Merged into Main Screen(#1499)

- android/app/src/main/java/org/fossasia/openevent/adapters/BaseRVAdapter.java
- android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java
Fixes #1681
Changes: 
Not showing sessions in draft state.
-
> fix: not showing sessions in draft state

- android/app/src/main/res/layout/activity_sessions_detail.xml
- android/app/src/main/res/layout/activity_speakers.xml
- android/app/src/main/res/layout/bookmark_widget.xml
- android/app/src/main/res/layout/content_session_detail.xml
- android/app/src/main/res/layout/fragment_about.xml
- android/app/src/main/res/layout/fragment_schedule.xml
- android/app/src/main/res/layout/item_location.xml
- android/app/src/main/res/layout/item_schedule.xml
- android/app/src/main/res/layout/item_session_speaker.xml
- android/app/src/main/res/layout/item_speaker.xml
- android/app/src/main/res/layout/item_sponsor.xml
- android/app/src/main/res/layout/item_sponsor_type.xml
- android/app/src/main/res/layout/item_track.xml
- android/app/src/main/res/layout/list_schedule.xml
- android/app/src/main/res/layout/recycler_view_header.xml
- android/app/src/main/res/layout/search_item_speaker.xml
- android/app/src/main/res/layout/search_result_type_header_format.xml
- android/app/src/main/res/layout/tracksactvity_item.xml
- android/app/src/main/res/values/dimens.xml
Fixes #1657 
Changes: 
Maintained the text size throughout the app. Also moved all the constant values from layout to dimens.xml.
-
> fix: maintaining text size throughout the app

- android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
- android/app/src/main/res/layout-sw600dp/activity_main.xml
Fixes #1578 
Changes: 
added a two pane layout
-
Its not complete, just wanted to get feedback from you guys as work goes on.
> feat: added two-pane layout
